export const IS_VOLUME_EXAGGERATED = 1;
export const VOLUME_EXAGERATION_SCALAR = 5000;

export const RADIUS_OF_EARTH = 6378.1 * 1000;
export const ONE_MILE_IN_METERS = 1.60934 * 1000;
export const LOW_EARTH_ORBIT_MIDPOINT_ALTITUDE = 1090 * ONE_MILE_IN_METERS;
export const MEDIUM_EARTH_ORBIT_MIDPOINT_ALTITUDE = 11718 * ONE_MILE_IN_METERS;
export const GEOSYNCHRONOUS_ORBIT_ALTITUDE = 22236 * ONE_MILE_IN_METERS;
export const HIGH_EARTH_ORBIT_MIDPOINT_ALTITUDE = 35768 * ONE_MILE_IN_METERS;
export const ISS_ORBIT_ALTITUDE = 408000;

export const MASS_OF_EARTH = 5.972 * Math.pow(10, 24);
